# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: WildFly Quickstarts CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
jobs:
  Test-build-default-matrix:
    name: BUILD DEFAULT - JDK${{ matrix.jdk }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [11, 17]
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        path: quickstarts
    - name: Set up JDK ${{ matrix.java }}
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.jdk }}
        impl: hotspot
    - name: Build Quickstarts
      run: |
        cd quickstarts
        mvn -U -B -fae clean install -Drelease
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: surefire-reports-JDK${{ matrix.jdk }}-${{ matrix.os }}
        path: 'quickstarts/**/surefire-reports/*.txt'

  Test-build-with-deps-matrix:
    name: BUILD WITH DEPS - JDK${{ matrix.jdk }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [11, 17]
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: n1hility/cancel-previous-runs@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        repository: wildfly/wildfly
        path: wildfly
    - uses: actions/checkout@v2
      with:
        repository: wildfly/boms
        path: boms
    - uses: actions/checkout@v2
      with:
        path: quickstarts
    - name: Set up JDK ${{ matrix.java }}
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.jdk }}
        impl: hotspot
    - name: Build Server
      run: |
        cd wildfly
        mvn -U -B -fae -DskipTests clean install
      shell: bash
    - name: Get Server Version
      run: |
        cd wildfly
        echo "VERSION_SERVER=$(mvn -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      shell: bash
    - name: Build BOMs with Server Version
      run: |
        cd boms
        mvn -U -B -fae clean install -Dversion.server=${{ env.VERSION_SERVER }}
      shell: bash
    - name: Get BOMs Version
      run: |
        cd boms
        echo "VERSION_BOMS=$(mvn -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      shell: bash
    - name: Build Quickstarts with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean install -Drelease -Dversion.server.bom=${{ env.VERSION_BOMS }} -Dversion.microprofile.bom=${{ env.VERSION_BOMS }} -Dversion.server.bootable-jar=${{ env. VERSION_SERVER }}
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: surefire-reports-JDK${{ matrix.jdk }}-${{ matrix.os }}
        path: 'quickstarts/**/surefire-reports/*.txt'
